import type { Metadata, Viewport } from "next";
import { MotionConfig } from "framer-motion";
import { SiteChrome } from "@/components/SiteChrome";
import { Toaster } from "@/components/Toast";
import { api } from "@/lib/api";

// Self-hosted fonts via @fontsource instead of next/font/google.
// next/font/google fetches the font files from Google's servers at
// dev/build time, and Turbopack has a well-documented bug parsing some of
// the URL formats Google's CSS API returns ("Module not found: Can't
// resolve '@vercel/turbopack-next/internal/font/google/font'" /
// "next/font/google queries have exactly one entry") — it's not caused by
// anything in this app and isn't reliably fixed by clearing .next. Pulling
// the font files from node_modules at build time sidesteps the live fetch
// entirely. The actual --font-display / --font-ui CSS variables (previously
// auto-generated by next/font/google's `.variable` option) are now defined
// by hand in styles/tokens.css, right next to the rest of the design tokens.
import "@fontsource/fraunces/400.css";
import "@fontsource/fraunces/600.css";
import "@fontsource/fraunces/700.css";
import "@fontsource/hanken-grotesk/400.css";
import "@fontsource/hanken-grotesk/500.css";
import "@fontsource/hanken-grotesk/600.css";
import "@fontsource/hanken-grotesk/700.css";
import "@/styles/tokens.css";

export const metadata: Metadata = {
  metadataBase: new URL("https://madhuroil.in"),
  title: { default: "Madhur Mini Oil Mill", template: "%s | Madhur Mini Oil Mill" },
  description: "Groundnut, sesame and cottonseed oil pressed and filtered at our mill in Rajkot, packed the same week.",
  openGraph: { type: "website", locale: "en_IN" },
};

export const viewport: Viewport = { width: "device-width", initialScale: 1, viewportFit: "cover" };

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  // Fetched once per request and passed down — Navbar's oil links, the
  // mobile drawer's oil list and the footer's Shop column all read from
  // this same list, so they can never drift out of sync with each other.
  const oils = await api.oils();

  return (
    <html lang="en-IN">
      {/* suppressHydrationWarning here only silences attribute-level mismatches
          on this exact element (e.g. Grammarly's data-gr-ext-installed /
          data-new-gr-c-s-check-loaded, injected into <body> by the extension
          before React hydrates) — it does not hide real hydration bugs
          elsewhere in the tree, and does not suppress mismatches in children. */}
      <body suppressHydrationWarning>
        <MotionConfig reducedMotion="user">
          <SiteChrome oils={oils}>{children}</SiteChrome>
          <Toaster />
        </MotionConfig>
      </body>
    </html>
  );
}
